// MIDI Constants
pub const NORMAL_TO_BOOL_SWITCH_ON_VALUE: f32 = 0.5;
pub const PITCH_BEND_AMOUNT_ZERO_POINT: u16 = 8192;
pub const PITCH_BEND_AMOUNT_MAX_VALUE: u16 = 16383;
pub const CENTS_PER_SEMITONE: u16 = 100;
pub const MIN_PITCH_BEND_RANGE: u8 = 2;
pub const MAX_PITCH_BEND_RANGE: u8 = 12;
pub const LEVEL_CURVE_LINEAR_RANGE: f32 = 1000.0; // Level range is -60 to 0 = 60dbfs so 10^(60/20) = 1000x
pub const MAX_MIDI_KEY_VELOCITY: f32 = 1.0;
pub const DEFAULT_VELOCITY_CURVE: f32 = 1.0;
pub const MIN_VELOCITY_CURVE_EXPONENT: f32 = 0.25;
pub const MAX_VELOCITY_CURVE_EXPONENT: f32 = 4.0;
pub const LINEAR_VELOCITY_CURVE_EXPONENT: f32 = 1.0;

// Envelope Constants
pub const ENVELOPE_INDEX_AMP: i32 = 0;
pub const ENVELOPE_INDEX_FILTER: i32 = 1;

// LFO Constants
pub const DEFAULT_VIBRATO_LFO_RATE: f32 = 10.0;
pub const DEFAULT_VIBRATO_LFO_CENTER_FREQUENCY: f32 = 1.0;
pub const DEFAULT_VIBRATO_LFO_DEPTH: f32 = 0.0;
pub const LFO_INDEX_MOD_WHEEL: i32 = 0;
pub const LFO_INDEX_FILTER: i32 = 1;

// Audio Constants
pub const SAMPLE_PRODUCER_LOOP_SLEEP_DURATION_MICROSECONDS: u64 = 100;

// MISC Constants
pub const SYNTHESIZER_MESSAGE_SENDER_CAPACITY: usize = 10;
