#[derive(Debug, Clone, PartialEq)]
pub enum UIUpdates {
    MidiScreen(String),
    MidiPortList(Vec<String>),
    MidiPortIndex(i32),
    MidiChannelIndex(i32),
    AudioDeviceList(Vec<String>),
    AudioDeviceIndex(i32),
    AudioDeviceChannelCount(u16),
    AudioDeviceChannelIndexes { left: i32, right: i32 },
    AudioDeviceSampleRateIndex(i32),
    AudioDeviceBufferSizeIndex(i32),
    OscillatorWaveShape(i32, i32),
    OscillatorFineTune(i32, f32, i32),
    OscillatorFineTuneCents(i32, i32),
    OscillatorCourseTune(i32, i32),
    OscillatorClipperBoost(i32, f32),
    OscillatorParameter1(i32, f32),
    OscillatorParameter2(i32, f32),
    LFOFrequency(i32, f32),
    LFOFrequencyDisplay(i32, f32),
    LFOPhase(i32, f32),
    LFOWaveShape(i32, f32),
    EnvelopeAttackTime(i32, f32),
    EnvelopeDecayTime(i32, f32),
    EnvelopeSustainLevel(i32, f32),
    EnvelopeReleaseTime(i32, f32),
    EnvelopeInverted(i32, f32),
    FilterCutoff(f32),
    FilterResonance(f32),
    FilterPoles(f32),
    FilterKeyTracking(f32),
    FilterEnvelopeAmount(f32),
    FilterLFOAmount(f32),
    OutputMixerBalance(f32),
    OutputMixerLevel(f32),
    OutputMixerIsMuted(f32),
    OscillatorMixerBalance(i32, f32),
    OscillatorMixerLevel(i32, f32),
    OscillatorMixerIsMuted(i32, f32),
    PortamentoTime(f32),
    PortamentoEnabled(f32),
    PitchBendRange(f32),
    VelocityCurve(f32),
    HardSync(f32),
    KeySync(f32),
    Effect(i32, bool, f32, f32, f32, f32),
}

#[derive(Debug, Clone, Copy)]
pub enum EnvelopeStage {
    Attack,
    Decay,
    Sustain,
    Release,
}
