include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
- test
- security
- semgrep
- sonar


semgrep:
  stage: semgrep
  image: semgrep/semgrep
  script:
    - semgrep ci --code
    - semgrep ci --gitlab-sast --gitlab-sast-output=./gl-sast-report.json
  variables:
    SEMGREP_APP_TOKEN: "$SEMGREP_APP_TOKEN"
  artifacts:
    paths:
      - gl-sast-report.json

sonarcloud:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.organization="$ORGANIZATION" -Dsonar.projectKey="$PROJECTKEY"
  variables:
    SONAR_HOST_URL: "$SONAR_HOST_URL"
    SONAR_TOKEN: "$SONAR_TOKEN"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0" 
