import {
    Panel,
    LabeledVerticalSlider,
    IntSpinBox,
    CenteredParameterSlider,
    HorizontalParameterSlider,
    PanelLabel,
    VerticalSpacer,
    HorizontalSpacer,
    SectionLabel,
    EnvelopeSection,
    FixedCenterLFOSection,
    EnvelopeValues,
    LFOValues,
} from "components.slint";
import {
    VerticalSlider,
    HorzontalSlider,
    BalanceSlider,
} from "custom-widgets.slint";
import { Switch } from "std-widgets.slint";
import { Theme } from "theme.slint";
import { Constant, PatchState } from "constants.slint";

export struct FilterCutoff {
    cutoff: float,
    resonance: float,
}

export struct FilterOptions {
    poles: int,
    key-track: float,
    envelope-amount: float,
    lfo-amount: float,
}

export component FilterCutoffSection inherits HorizontalLayout {
    in property <FilterCutoff> filter-cutoff-values;
    callback filter-cutoff-changed(float);
    callback filter-resonance-changed(float);

    alignment: start;

    LabeledVerticalSlider {
        label: Theme.filter-label-cutoff;
        slider-height: 220px;
        slider-width: 50px;
        value: filter-cutoff-values.cutoff;
        vertical-slider-changed(frequency) => {
            filter-cutoff-changed(frequency);
        }
    }

    LabeledVerticalSlider {
        label: Theme.filter-label-resonance;
        slider-width: 50px;
        slider-height: 220px;
        value: filter-cutoff-values.resonance;
        vertical-slider-changed(amount) => {
            filter-resonance-changed(amount);
        }
    }
}

export component FilterOptionsSection inherits VerticalLayout {
    in property <FilterOptions> filter-options-values;
    property <int> patch_generation: PatchState.generation;
    property <float> key-track-live;
    property <float> poles-live;
    property <float> envelope-amount-live;
    property <float> lfo-amount-live;

    callback filter-poles-changed(float);
    callback filter-key-tracking-changed(float);
    callback filter-envelope-amount-changed(float);
    callback filter-lfo-amount-changed(float);

    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;
    alignment: start;

    function normalized_poles_to_slope(normalized_poles: float) -> int {
        // normalized_poles = 0.0 - 1.0
        // normalized_poles * 3 gives 4 pole values but zero based.
        // + 1 makes it 1 based
        // * 6 converts to slope as there are 6 db/octave/pole
        ((normalized_poles * 3) + 1) * 6
    }

    init => {
        key-track-live = filter-options-values.key-track;
        poles-live = filter-options-values.poles;
        envelope-amount-live = filter-options-values.envelope-amount;
        lfo-amount-live = filter-options-values.lfo-amount;
    }

    changed patch_generation => {
        key-track-live = filter-options-values.key-track;
        poles-live = filter-options-values.poles;
        envelope-amount-live = filter-options-values.envelope-amount;
        lfo-amount-live = filter-options-values.lfo-amount;
    }

    poles := IntSpinBox {
        label: Theme.filter-label-poles;
        value-units: Theme.filter-label-slope;
        display-value: normalized_poles_to_slope(poles-live);
        show-value: true;
        show-units: true;
        height: 50px;
        step: 1;
        minimum: 1;
        maximum: 4;
        value: filter-options-values.poles;
        spinbox-width: Theme.filter-panel-widget-width;
        spinbox-changed(poles) => {
            poles-live = poles;
            filter-poles-changed(poles);
        }
    }

    keytrack := CenteredParameterSlider {
        label: Theme.filter-label-key-tracking;
        display-value: round((key-track-live - 0.5) * 200);
        value-units: Theme.controls-unit-percent;
        show-value: true;
        show-units: true;
        slider-width: Theme.filter-panel-widget-width;
        value: filter-options-values.key-track;
        centered-parameter-slider-changed(amount) => {
            key-track-live = amount;
            filter-key-tracking-changed(amount);
        }
    }

    envelope_amount := HorizontalParameterSlider {
        label: Theme.filter-label-envelope-amount;
        display-value: round(envelope-amount-live * 100);
        value-units: Theme.controls-unit-percent;
        show-value: true;
        show-units: true;
        value: filter-options-values.envelope-amount;
        slider-width: Theme.filter-panel-widget-width;
        horizontal-parameter-slider-changed(amount) => {
            envelope-amount-live = amount;
            filter-envelope-amount-changed(amount);
        }
    }

    lfo_amount := HorizontalParameterSlider {
        label: Theme.filter-label-lfo-amount;
        display-value: round(lfo-amount-live * 100);
        value-units: Theme.controls-unit-percent;
        show-value: true;
        show-units: true;
        value: filter-options-values.lfo-amount;
        slider-width: Theme.filter-panel-widget-width;
        horizontal-parameter-slider-changed(amount) => {
            lfo-amount-live = amount;
            filter-lfo-amount-changed(amount);
        }
    }
}

export component FilterEnvelopeSection inherits VerticalLayout {

    in property <EnvelopeValues> filter-envelope-values;

    callback envelope-attack-changed(float);
    callback envelope-decay-changed(float);
    callback envelope-sustain-changed(float);
    callback envelope-release-changed(float);
    callback envelope-invert-changed(bool);

    alignment: start;
    spacing: 5px;

    HorizontalLayout {
        SectionLabel {
            label: Theme.filter-section-label-envelope;
        }
    }

    EnvelopeSection {
        envelope-values: filter-envelope-values;
        envelope-attack-changed(milliseconds) => {
            envelope-attack-changed(milliseconds);
        }
        envelope-decay-changed(milliseconds) => {
            envelope-decay-changed(milliseconds);
        }
        envelope-sustain-changed(level) => {
            envelope-sustain-changed(level);
        }
        envelope-release-changed(milliseconds) => {
            envelope-release-changed(milliseconds);
        }
        envelope-invert-changed(is_active) => {
            envelope-invert-changed(is_active);
        }
    }
}

export component FilterPanel inherits Panel {

    in property <FilterCutoff> filter-cutoff-values;
    in property <FilterOptions> filter-options-values;
    in property <EnvelopeValues> filter-envelope-values;
    in property <LFOValues> filter-lfo-values;
    in property <int> filter-lfo-phase-display;
    in property <float> filter-lfo-frequency-display;

    callback filter-cutoff-changed(float);
    callback filter-resonance-changed(float);
    callback filter-poles-changed(float);
    callback filter-key-tracking-changed(float);
    callback filter-envelope-amount-changed(float);
    callback filter-lfo-amount-changed(float);
    callback envelope-attack-changed(int, float);
    callback envelope-decay-changed(int, float);
    callback envelope-sustain-changed(int, float);
    callback envelope-release-changed(int, float);
    callback envelope-invert-changed(int, bool);
    callback lfo-frequency-changed(int, float);
    callback lfo-shape-changed(int, int);
    callback lfo-phase-changed(int, float);
    callback lfo-phase-reset(int);
    callback lfo-clock-sync-enabled(int, bool);
    callback lfo-key-sync-enabled(int, bool);

    VerticalLayout {
        padding: Theme.osc-controls-panel-padding;
        spacing: Theme.osc-controls-panel-spacing;
        alignment: start;

        PanelLabel {
            label: Theme.filter-panel-label;
        }

        HorizontalLayout {
            FilterCutoffSection {
                filter-cutoff-values: filter-cutoff-values;
                filter-cutoff-changed(frequency) => {
                    filter-cutoff-changed(frequency);
                }
                filter-resonance-changed(frequency) => {
                    filter-resonance-changed(frequency);
                }
            }

            VerticalSpacer { }

            FilterOptionsSection {
                filter-options-values: filter-options-values;
                filter-poles-changed(poles) => {
                    filter-poles-changed(poles);
                }
                filter-key-tracking-changed(amount) => {
                    filter-key-tracking-changed(amount);
                }
                filter-envelope-amount-changed(amount) => {
                    filter-envelope-amount-changed(amount);
                }
                filter-lfo-amount-changed(amount) => {
                    filter-lfo-amount-changed(amount);
                }
            }
        }

        HorizontalSpacer { }

        FilterEnvelopeSection {
            filter-envelope-values: filter-envelope-values;
            envelope-attack-changed(milliseconds) => {
                envelope-attack-changed(Constant.ENVELOPE_FILTER_INDEX, milliseconds);
            }
            envelope-decay-changed(milliseconds) => {
                envelope-decay-changed(Constant.ENVELOPE_FILTER_INDEX, milliseconds);
            }
            envelope-sustain-changed(level) => {
                envelope-sustain-changed(Constant.ENVELOPE_FILTER_INDEX, level);
            }
            envelope-release-changed(milliseconds) => {
                envelope-release-changed(Constant.ENVELOPE_FILTER_INDEX, milliseconds);
            }
            envelope-invert-changed(is_active) => {
                envelope-invert-changed(Constant.ENVELOPE_FILTER_INDEX, is_active);
            }
        }

        HorizontalSpacer { }

        HorizontalLayout {
            SectionLabel {
                label: Theme.filter-section-label-lfo;
            }
        }

        FixedCenterLFOSection {
            lfo-values: filter-lfo-values;
            lfo-phase-display: filter-lfo-phase-display;
            lfo-frequency-display: filter-lfo-frequency-display;

            lfo-frequency-changed(frequency) => {
                lfo-frequency-changed(Constant.LFO_FILTER_INDEX, frequency);
            }
            lfo-shape-changed(shape) => {
                lfo-shape-changed(Constant.LFO_FILTER_INDEX, shape);
            }
            lfo-phase-changed(phase) => {
                lfo-phase-changed(Constant.LFO_FILTER_INDEX, phase);
            }
            lfo-phase-reset() => {
                lfo-phase-reset(Constant.LFO_FILTER_INDEX);
            }
            lfo-clock-sync-enabled(is-enabled) => {
                lfo-clock-sync-enabled(Constant.LFO_FILTER_INDEX, is-enabled);
            }
            lfo-key-sync-enabled(is-enabled) => {
                lfo-key-sync-enabled(Constant.LFO_FILTER_INDEX, is-enabled);
            }
        }

        HorizontalSpacer { }
    }
}
