import {
    Panel,
    DropDownMenu,
    VerticalSpacer,
    HorizontalControlLabel,
} from "components.slint";
import { Theme } from "theme.slint";
import { Button, ComboBox, HorizontalBox } from "std-widgets.slint";
import {
    SettingsIcon,
    SettingsWindow,
    AudioDevice,
    MidiPort,
} from "settings-panel.slint";

export component Version inherits Text {
    in property <string> version;
    vertical-alignment: bottom;
    font-size: Theme.header-version-font-size;
    text: Theme.header-version-prefix + version;
}

export component Logo inherits Image {
    source: Theme.header-logo;
    horizontal-alignment: Theme.header-logo-alignment;
    height: Theme.header-logo-height;
    width: Theme.header-logo-width;
}

export component Patches inherits HorizontalLayout {
    in property <string> title;
    in property <[string]> patch-list;
    in property <int> selected-index;
    callback patch-changed(int);

    VerticalLayout {
        alignment: center;
        HorizontalControlLabel {
            label: "Patches";
        }
    }

    preset := ComboBox {
        height: 25px;
        width: Theme.oscillator-panel-widget-width;
        model: patch-list;
        current-index: selected-index;

        selected(value) => {
            patch-changed(self.current-index);
        }
    }
}

export component HeaderPanel inherits Panel {
    in property <string> version;
    in property <AudioDevice> audio-device-values;
    in property <MidiPort> midi-port-values;
    in property <[string]> patch-list;
    in-out property <int> selected-patch-index;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);
    callback audio-buffer-size-changed(string);
    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);
    callback patch-changed(int);
    callback patch-saved(string);

    height: Theme.header-panel-height;
    background: Theme.header-panel-background;

    settings := SettingsWindow {
        audio-device-values: audio-device-values;
        midi-port-values: midi-port-values;

        audio-output-device-changed(device) => {
            audio-output-device-changed(device);
        }
        audio-output-left-channel-changed(left) => {
            audio-output-left-channel-changed(left);
        }
        audio-output-right-channel-changed(right) => {
            audio-output-right-channel-changed(right);
        }
        audio-sample-rate-changed(rate) => {
            audio-sample-rate-changed(rate);
        }
        audio-buffer-size-changed(size) => {
            audio-buffer-size-changed(size);
        }
        midi-input-port-changed(port) => {
            midi-input-port-changed(port);
        }
        midi-input-channel-changed(channel) => {
            midi-input-channel-changed(channel);
        }
        patch-saved(name) => {
            patch-saved(name);
        }
    }

    HorizontalLayout {

        padding: Theme.header-panel-padding;
        spacing: Theme.header-panel-spacing;

        alignment: space-between;

        logo := Logo { }

        patches := Patches {
            title: Theme.settings-patches-label;
            patch-list: patch-list;
            selected-index: selected-patch-index;

            patch-changed(patch_index) => {
                patch-changed(patch_index)
            }
        }

        HorizontalLayout {
            Version {
                version: version;
            }

            VerticalSpacer { }

            SettingsIcon {
                open-settings => {
                    settings.show();
                }
            }
        }
    }
}
