import { Panel, VerticalSpacer } from "components.slint";
import { Theme } from "theme.slint";
import { Button } from "std-widgets.slint";
import {
    SettingsIcon,
    SettingsWindow,
    AudioDevice,
    MidiPort,
} from "settings-panel.slint";

export component Version inherits Text {
    in property <string> version;
    vertical-alignment: bottom;
    font-size: Theme.header-version-font-size;
    text: Theme.header-version-prefix + version;
}

export component Logo inherits Image {
    source: Theme.header-logo;
    horizontal-alignment: Theme.header-logo-alignment;
    height: Theme.header-logo-height;
}

export component HeaderPanel inherits Panel {
    in property <string> version;
    in property <AudioDevice> audio-device-values;
    in property <MidiPort> midi-port-values;
    in property <[string]> preset-list;
    in-out property <int> selected-preset-index;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);
    callback audio-buffer-size-changed(string);
    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);
    callback preset-changed(int);
    callback patch-saved(string);

    height: Theme.header-panel-height;
    background: Theme.header-panel-background;

    settings := SettingsWindow {
        audio-device-values: audio-device-values;
        midi-port-values: midi-port-values;
        preset-list: preset-list;
        selected-preset-index: selected-preset-index;

        audio-output-device-changed(device) => {
            audio-output-device-changed(device);
        }
        audio-output-left-channel-changed(left) => {
            audio-output-left-channel-changed(left);
        }
        audio-output-right-channel-changed(right) => {
            audio-output-right-channel-changed(right);
        }
        audio-sample-rate-changed(rate) => {
            audio-sample-rate-changed(rate);
        }
        audio-buffer-size-changed(size) => {
            audio-buffer-size-changed(size);
        }
        midi-input-port-changed(port) => {
            midi-input-port-changed(port);
        }
        midi-input-channel-changed(channel) => {
            midi-input-channel-changed(channel);
        }
        preset-changed(preset_index) => {
            root.selected-preset-index = preset_index;
            preset-changed(preset-index);
        }
        patch-saved(name) => {
            patch-saved(name);
        }
    }

    HorizontalLayout {
        padding: Theme.header-panel-padding;
        spacing: Theme.header-panel-spacing;
        alignment: space-between;

        Logo { }

        header-spacer := Rectangle { }

        Version {
            version: version;
        }

        VerticalSpacer { }

        SettingsIcon {
            open-settings => {
                settings.show();
            }
        }
    }
}
