import { Theme } from "theme.slint";
import { Constant } from "constants.slint";
import {
    MomentaryButton,
    Panel,
    PanelLabel,
    ComponentLabel,
    DropDownMenu,
    HorizontalSpacer,
    VerticalControlLabel,
    TextInput,
    ToggleSwitch,
} from "components.slint";
import { Button, StandardButton } from "std-widgets.slint";

export struct AudioDevice {
    output-devices: [string],
    output-device-index: int,
    left-channels: [string],
    left-channel-index: int,
    right-channels: [string],
    right-channel-index: int,
    sample-rates: [string],
    sample-rate-index: int,
    buffer-sizes: [string],
    buffer-size-index: int,
}

export struct MidiPort {
    input-ports: [string],
    input-port-index: int,
    channels: [string],
    channel-index: int,
}

export struct PatchStatus { status: bool, message: string}


export component AudioSettings inherits VerticalLayout {

    in property <AudioDevice> audio-device-values;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);
    callback audio-buffer-size-changed(string);
    callback reload-popupwindow();

    padding: Theme.settings-panel-padding;
    spacing: Theme.settings-panel-spacing;

    changed audio-device-values => {
        reload-popupwindow();
    }

    PanelLabel {
        label: Theme.settings-audio-settings-title;
    }

    device := DropDownMenu {
        label: "Output Device";
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.output-devices;
        value-index: audio-device-values.output-device-index;
        drop_down_changed(index, device) => {
            audio-output-device-changed(device);
        }
    }

    HorizontalLayout {
        padding: Theme.settings-panel-padding;
        spacing: Theme.settings-panel-spacing;

        left := DropDownMenu {
            label: "Left Channel";
            value-list: audio-device-values.left-channels;
            value-index: audio-device-values.left-channel-index;
            drop_down_changed(index, left) => {
                audio-output-left-channel-changed(left);
            }
        }

        right := DropDownMenu {
            label: "Right Channel";
            value-list: audio-device-values.right-channels;
            value-index: audio-device-values.right-channel-index;
            drop_down_changed(index, right) => {
                audio-output-right-channel-changed(right);
            }
        }
    }

    sample := DropDownMenu {
        label: "Sample Rate";
        enabled: true;
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.sample-rates;
        value-index: audio-device-values.sample-rate-index;
        drop_down_changed(index, rate) => {
            audio-sample-rate-changed(rate);
        }
    }

    buffer_size := DropDownMenu {
        label: "Buffer Size";
        enabled: true;
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.buffer_sizes;
        value-index: audio-device-values.buffer_size-index;
        drop_down_changed(index, size) => {
            audio-buffer-size-changed(size);
        }
    }
}

export component MidiSettings inherits VerticalLayout {
    in property <MidiPort> midi-port-values;

    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);
    callback reload-popupwindow();

    changed midi-port-values => {
        reload-popupwindow();
    }

    padding: Theme.settings-panel-padding;
    spacing: Theme.settings-panel-spacing;

    PanelLabel {
        label: Theme.settings-midi-settings-title;
    }

    port := DropDownMenu {
        label: "Input Port";
        value-list: midi-port-values.input-ports;
        value-index: midi-port-values.input-port-index;
        dropdown-width: Theme.oscillator-panel-widget-width;
        drop_down_changed(index, left) => {
            midi-input-port-changed(left);
        }
    }

    channel := DropDownMenu {
        label: "Channel";
        value-list: midi-port-values.channels;
        value-index: midi-port-values.channel-index;
        dropdown-width: Theme.oscillator-panel-widget-width;
        drop_down_changed(index, left) => {
            midi-input-channel-changed(left);
        }
    }
}

export component SynthSettings inherits VerticalLayout {
    in-out property <bool> polarity-is-flipped: false;
    callback polarity-flipped(bool);

    padding: Theme.settings-panel-padding;
    spacing: Theme.settings-panel-spacing;

    PanelLabel {
        label: Theme.settings-synth-options-title;
    }

    ToggleSwitch {
        label: Theme.osc-options-polarity;
        is_checked: polarity-is-flipped;
        toggle_switch_updated(is_flipped) => {
            polarity-flipped(is_flipped);
        }
    }
}

export component PatchSaveSettings inherits VerticalLayout {
    in property <PatchStatus> patch-save-status;
    callback patch-saved(string);

    PanelLabel {
        label: Theme.settings-patches-presets-title;
    }

    patch-name := TextInput {
        label: Theme.settings-patch-name;
    }

    HorizontalLayout {
        alignment: center;
        save := MomentaryButton {
            label: Theme.settings-patch-save;
            button-width: 100px;
            button-height: 27px;
            momentary-button-pressed => {
                if (patch-name.text != "") {
                    patch-saved(patch-name.text);
                    patch-name.text = "";
                    save-status.visible = true;
                }
            }
        }
    }

    HorizontalLayout {
        alignment: space-evenly;
        save-status := Text {
            text: patch-save-status.message;
            color: patch-save-status.status ? green : red;
            visible: false;
        }
    }
}

export component PatchDeleteSettings inherits VerticalLayout {
    in property <PatchStatus> patch-delete-status;
    in property <[string]> user-patch-list;

    callback patch-deleted(int);

    property <int> new-patch-index;

    padding: Theme.settings-panel-padding;
    spacing: Theme.settings-panel-spacing;

    PanelLabel {
        label: Theme.settings-delete-patches-title;
    }

    HorizontalLayout {
        alignment: center;
        patch-to-delete := DropDownMenu {
            dropdown-width: Theme.oscillator-panel-widget-width;
            value-list: user-patch-list;
            drop_down_changed(index, name) => {
                new-patch-index = index;
            }
        }
    }

    HorizontalLayout {
        alignment: center;
        delete := MomentaryButton {
            label: Theme.settings-patch-delete;
            button-width: 100px;
            button-height: 27px;
            momentary-button-pressed => {
                patch-deleted(new-patch-index);
                delete-status.visible = true;
            }
        }
    }

    HorizontalLayout {
        alignment: space-evenly;
        delete-status := Text {
            text: patch-delete-status.message;
            color: patch-delete-status.status ? green : red;
            visible: false;
        }
    }
}

export component SettingsIcon inherits Image {
    source: Theme.settings-image;
    height: Theme.header-logo-height;
    width: Theme.header-logo-height;
    colorize: touch.pressed ? black : transparent;
    callback open-settings();

    touch := TouchArea {
        changed pressed => {
            if (self.pressed) {
                open-settings();
            }
        }
    }
}

export component SettingsWindow inherits PopupWindow {
    in property <AudioDevice> audio-device-values;
    in property <MidiPort> midi-port-values;
    in-out property <int> selected-preset-index;
    in-out property <int> selected-patch-index;
    in property <PatchStatus> patch-save-status;
    in property <PatchStatus> patch-delete-status;
    in property <bool> polarity-is-flipped;
    in property <[string]> user-patch-list;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);
    callback audio-buffer-size-changed(string);
    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);
    callback patch-saved(string);
    callback patch-deleted(int);
    callback polarity-flipped(bool);

    width: Theme.settings-panel-width;
    height: Theme.settings-panel-height;
    x: Theme.window-width / 2 - Theme.settings-panel-width / 2;
    y: Theme.settings-panel-y-position;
    close-policy: no-auto-close;

    Rectangle {
        background: Theme.settings-window-background;
        border-width: Theme.settings-window-border-width;
        border-color: Theme.settings-window-border-colour;
        border-bottom-left-radius: Theme.settings-window-border-radius;
        border-bottom-right-radius: Theme.settings-window-border-radius;
        border-top-left-radius: Theme.settings-window-border-radius;
        border-top-right-radius: Theme.settings-window-border-radius;

        VerticalLayout {
            padding: Theme.settings-panel-padding;
            spacing: Theme.settings-panel-spacing;
            alignment: start;

            HorizontalLayout {
                padding: Theme.settings-panel-padding;
                spacing: Theme.settings-panel-spacing;
                alignment: start;

                VerticalLayout {
                    alignment: start;
                    padding: Theme.settings-panel-padding;
                    spacing: Theme.settings-panel-spacing;

                    AudioSettings {
                        audio-device-values: audio-device-values;

                        reload-popupwindow() => {
                            root.show();
                        }

                        audio-output-device-changed(device) => {
                            audio-output-device-changed(device);
                        }
                        audio-output-left-channel-changed(left) => {
                            audio-output-left-channel-changed(left);
                        }
                        audio-output-right-channel-changed(right) => {
                            audio-output-right-channel-changed(right);
                        }
                        audio-sample-rate-changed(rate) => {
                            audio-sample-rate-changed(rate);
                        }
                        audio-buffer-size-changed(size) => {
                            audio-buffer-size-changed(size);
                        }
                    }

                    HorizontalSpacer {
                        top-padding: Theme.settings-panel-padding;
                    }

                    MidiSettings {
                        midi-port-values: midi-port-values;

                        reload-popupwindow() => {
                            root.show();
                        }

                        midi-input-port-changed(port) => {
                            midi-input-port-changed(port);
                        }
                        midi-input-channel-changed(channel) => {
                            midi-input-channel-changed(channel);
                        }
                    }
                }

                VerticalLayout {
                    alignment: start;
                    padding: Theme.settings-panel-padding;
                    spacing: Theme.settings-panel-spacing;

                    SynthSettings {
                        polarity-is-flipped: polarity-is-flipped;

                        polarity-flipped(is_flipped) => {
                            polarity-flipped(is_flipped);
                        }
                    }

                    HorizontalSpacer {
                        top-padding: Theme.settings-panel-padding;
                    }

                    PatchSaveSettings {
                        patch-save-status: patch-save-status;
                        patch-saved(patch-name) => {
                            patch-saved(patch-name);
                        }
                    }

                    HorizontalSpacer {
                        top-padding: Theme.settings-panel-padding;
                    }

                    PatchDeleteSettings {
                        patch-delete-status: patch-delete-status;
                        user-patch-list: user-patch-list;

                        patch-deleted(index) => {
                            patch-deleted(index);
                        }
                    }
                }
            }

            StandardButton {
                kind: close;
                clicked => {
                    root.close();
                }
            }
        }
    }
}
