import { Theme } from "theme.slint";
import { Constant } from "constants.slint";
import {
    MomentaryButton,
    Panel,
    PanelLabel,
    ComponentLabel,
    DropDownMenu,
    HorizontalSpacer,
    VerticalControlLabel,
    TextInput,
} from "components.slint";
import { Button, StandardButton } from "std-widgets.slint";

export struct AudioDevice {
    output-devices: [string],
    output-device-index: int,
    left-channels: [string],
    left-channel-index: int,
    right-channels: [string],
    right-channel-index: int,
    sample-rates: [string],
    sample-rate-index: int,
    buffer-sizes: [string],
    buffer-size-index: int,
}

export struct MidiPort {
    input-ports: [string],
    input-port-index: int,
    channels: [string],
    channel-index: int,
}

export component AudioSettings inherits VerticalLayout {

    in property <AudioDevice> audio-device-values;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);
    callback audio-buffer-size-changed(string);
    callback reload-popupwindow();

    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;

    changed audio-device-values => {
        reload-popupwindow();
    }

    device := DropDownMenu {
        label: "Output Device";
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.output-devices;
        value-index: audio-device-values.output-device-index;
        drop_down_changed(index, device) => {
            audio-output-device-changed(device);
        }
    }

    HorizontalLayout {
        padding: Theme.osc-controls-panel-padding;
        spacing: Theme.osc-controls-panel-spacing;

        left := DropDownMenu {
            label: "Left Channel";
            value-list: audio-device-values.left-channels;
            value-index: audio-device-values.left-channel-index;
            drop_down_changed(index, left) => {
                audio-output-left-channel-changed(left);
            }
        }

        right := DropDownMenu {
            label: "Right Channel";
            value-list: audio-device-values.right-channels;
            value-index: audio-device-values.right-channel-index;
            drop_down_changed(index, right) => {
                audio-output-right-channel-changed(right);
            }
        }
    }

    sample := DropDownMenu {
        label: "Sample Rate";
        enabled: true;
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.sample-rates;
        value-index: audio-device-values.sample-rate-index;
        drop_down_changed(index, rate) => {
            audio-sample-rate-changed(rate);
        }
    }

    buffer_size := DropDownMenu {
        label: "Buffer Size";
        enabled: true;
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.buffer_sizes;
        value-index: audio-device-values.buffer_size-index;
        drop_down_changed(index, size) => {
            audio-buffer-size-changed(size);
        }
    }
}

export component MidiSettings inherits VerticalLayout {
    in property <MidiPort> midi-port-values;

    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);
    callback reload-popupwindow();

    changed midi-port-values => {
        reload-popupwindow();
    }

    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;

    port := DropDownMenu {
        label: "Input Port";
        value-list: midi-port-values.input-ports;
        value-index: midi-port-values.input-port-index;
        dropdown-width: Theme.oscillator-panel-widget-width;
        drop_down_changed(index, left) => {
            midi-input-port-changed(left);
        }
    }

    channel := DropDownMenu {
        label: "Channel";
        value-list: midi-port-values.channels;
        value-index: midi-port-values.channel-index;
        dropdown-width: Theme.oscillator-panel-widget-width;
        drop_down_changed(index, left) => {
            midi-input-channel-changed(left);
        }
    }
}

export component Presets inherits VerticalLayout {
    in property <string> title;
    in property <[string]> preset-list;
    in property <int> selected-index;
    callback preset-changed(int);

    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;

    preset := DropDownMenu {
        label: title;
        value-list: preset-list;
        value-index: selected-index;
        dropdown-width: Theme.oscillator-panel-widget-width;
        drop_down_changed(index, preset) => {
            preset-changed(index);
        }
    }
}

export component SettingsIcon inherits Image {
    source: Theme.settings-image;
    height: Theme.header-logo-height;
    width: Theme.header-logo-height;
    colorize: touch.pressed ? black : transparent;
    callback open-settings();

    touch := TouchArea {
        changed pressed => {
            if (self.pressed) {
                open-settings();
            }
        }
    }
}

export component SettingsWindow inherits PopupWindow {
    in property <AudioDevice> audio-device-values;
    in property <MidiPort> midi-port-values;
    in property <[string]> preset-list;
    in property <[string]> patch-list;
    in-out property <int> selected-preset-index;
    in-out property <int> selected-patch-index;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);
    callback audio-buffer-size-changed(string);
    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);
    callback preset-changed(int);
    callback patch-saved(string);

    width: Theme.settings-panel-width;
    height: Theme.settings-panel-height;
    x: Theme.window-width / 2 - Theme.settings-panel-width / 2;
    y: Theme.window-height / 2 - Theme.settings-panel-height / 2;
    close-policy: no-auto-close;

    Rectangle {
        background: Theme.settings-window-background;
        border-width: Theme.settings-window-border-width;
        border-color: Theme.settings-window-border-colour;
        border-bottom-left-radius: Theme.settings-window-border-radius;
        border-bottom-right-radius: Theme.settings-window-border-radius;
        border-top-left-radius: Theme.settings-window-border-radius;
        border-top-right-radius: Theme.settings-window-border-radius;

        VerticalLayout {
            padding: Theme.osc-controls-panel-padding;
            spacing: Theme.osc-controls-panel-spacing;
            alignment: start;

            HorizontalLayout {
                padding: Theme.osc-controls-panel-padding;
                spacing: Theme.osc-controls-panel-spacing;
                alignment: start;

                VerticalLayout {
                    padding: Theme.osc-controls-panel-padding;
                    spacing: Theme.osc-controls-panel-spacing;
                    alignment: start;

                    PanelLabel {
                        label: Theme.settings-audio-settings-title;
                    }

                    AudioSettings {
                        audio-device-values: audio-device-values;

                        reload-popupwindow() => {
                            root.show();
                        }

                        audio-output-device-changed(device) => {
                            audio-output-device-changed(device);
                        }
                        audio-output-left-channel-changed(left) => {
                            audio-output-left-channel-changed(left);
                        }
                        audio-output-right-channel-changed(right) => {
                            audio-output-right-channel-changed(right);
                        }
                        audio-sample-rate-changed(rate) => {
                            audio-sample-rate-changed(rate);
                        }
                        audio-buffer-size-changed(size) => {
                            audio-buffer-size-changed(size);
                        }
                    }
                }

                VerticalLayout {
                    padding: Theme.osc-controls-panel-padding;
                    spacing: Theme.osc-controls-panel-spacing;
                    alignment: start;

                    PanelLabel {
                        label: Theme.settings-midi-settings-title;
                    }

                    MidiSettings {
                        midi-port-values: midi-port-values;

                        reload-popupwindow() => {
                            root.show();
                        }

                        midi-input-port-changed(port) => {
                            midi-input-port-changed(port);
                        }
                        midi-input-channel-changed(channel) => {
                            midi-input-channel-changed(channel);
                        }
                    }
                }
            }

            PanelLabel {
                label: Theme.settings-patches-presets-title;
            }

            HorizontalLayout {
                alignment: space-evenly;

                VerticalLayout {
                    alignment: start;

                    presets := Presets {
                        title: Theme.settings-presets-label;
                        preset-list: preset-list;
                        selected-index: selected-preset-index;

                        preset-changed(preset_index) => {
                            preset-changed(preset_index)
                        }
                    }

                    patches := Presets {
                        title: Theme.settings-patches-label;
                        preset-list: patch-list;
                        selected-index: selected-patch-index;

                        preset-changed(patch_index) => {
                            preset-changed(patch_index)
                        }
                    }
                }

                HorizontalLayout {
                    alignment: center;
                    VerticalLayout {
                        alignment: start;
                        patch-name := TextInput {
                            label: Theme.settings-patch-name;
                        }

                        HorizontalLayout {
                            alignment: center;
                            save := MomentaryButton {
                                label: Theme.settings-patch-save;
                                button-width: 100px;
                                button-height: 27px;
                                momentary-button-pressed => {
                                    if (patch-name.text != "") {
                                        patch-saved(patch-name.text);
                                        patch-name.text = "";
                                        result-status.visible = true;
                                    }
                                }
                            }
                        }

                        HorizontalLayout {
                            alignment: space-evenly;
                            result-status := Text {
                                text: Theme.settings-saved-status;
                                visible: false;
                            }
                        }
                    }
                }
            }

            HorizontalSpacer { }

            StandardButton {
                kind: close;
                clicked => {
                    root.close();
                }
            }
        }
    }
}
