pub const PARAMETERS_PER_EFFECT: usize = 4;
pub const PARAMETER_DISABLED_VALUE: f32 = -1.0;
pub const MAX_WAVEFOLDER_THRESHOLD: f32 = 1.0;
pub const MAX_CLIPPER_THRESHOLD: f32 = 1.0;
pub const MAX_BITSHIFT_BITS: u32 = 16;
pub const MIN_BITSHIFT_BITS: u32 = 1;
