use coreaudio_sys::SInt32;

pub const DEFAULT_AUDIO_DEVICE_INDEX: usize = 0;
pub const DEFAULT_LEFT_CHANNEL_INDEX: i32 = 0;
pub const DEFAULT_RIGHT_CHANNEL_INDEX: i32 = 1;
pub const SAMPLE_BUFFER_SENDER_CAPACITY: usize = 5;
pub const AUDIO_MESSAGE_SENDER_CAPACITY: usize = 10;
pub const SAMPLE_BUFFER_CAPACITY: usize = 8192;
pub const OUTPUT_CHANNEL_DISABLED_VALUE: i32 = -1;
pub const USER_CHANNEL_TO_CHANNEL_INDEX_OFFSET: i32 = 1;
pub const MONO_CHANNEL_COUNT: u16 = 1;
pub const DEVICE_LIST_POLLING_INTERVAL_IN_MS: u64 = 20000;
pub const COREAUDIO_DEVICE_LIST_UPDATE_REST_PERIOD_IN_MS: u64 = 100;
pub const OSSSTATUS_NO_ERROR: SInt32 = 0;
