export global Constant {
    out property <float> DEFAULT_BALANCE: 0;
    out property <float> MAX_LEFT_BALANCE: 1;
    out property <float> MAX_RIGHT_BALANCE: -1;
    out property <float> SILENCE_LEVEL_DBFS: -70;
    out property <float> MAX_OUTPUT_LEVEL_DBFS: 0;
    out property <int> MIN_COURSE_TUNE_SEMITONES: -12;
    out property <int> MAX_COURSE_TUNE_SEMITONES: 12;
    out property <int> LFO_MAX_PHASE_DEGREES: 360;
    out property <int> ENVELOPE_AMP_INDEX: 0;
    out property <int> ENVELOPE_FILTER_INDEX: 1;
    out property <int> LFO_MOD_WHEEL_INDEX: 0;
    out property <int> LFO_FILTER_INDEX: 1;

    // Control Default Values
    out property <float> DEFAULT_OUTPUT_MIXER_LEVEL_NORMAL: 0.8;
    out property <float> DEFAULT_OSCILLATOR_LEVEL_NORMAL: 1.0;
    out property <float> DEFAULT_SUB_OSCILLATOR_LEVEL_NORMAL: 0.0;
    out property <float> DEFAULT_EG_MILLISECONDS_STAGE_NORMAL: 0.02;
    out property <float> DEFAULT_EG_SUSTAIN_LEVEL_NORMAL: 0.8;
    out property <float> DEFAULT_FILTER_CUTOFF_NORMAL: 1.0;
    out property <float> DEFAULT_FILTER_RESONANCE_NORMAL: 0.0;
    out property <int> DEFAULT_FILTER_POLES: 4;

    out property <[string]> OSC_WAVE_SHAPES: [
        "Sine",
        "Triangle",
        "Square",
        "Saw",
        "Pulse",
        "Ramp",
        "GigaSaw",
        "AM",
        "FM",
        "Noise"
    ];

    out property <[string]> LFO_WAVE_SHAPES: ["Sine", "Triangle", "Square", "Saw", "Ramp", "GigaSaw", "Noise"];

    out property <[string]> MIDI_CHANNELS: [
        "Omni",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16"
    ];
}
