export global Constant {
    out property <float> DEFAULT_BALANCE: 0;
    out property <float> MAX_LEFT_BALANCE: 1;
    out property <float> MAX_RIGHT_BALANCE: -1;
    out property <float> DEFAULT_OUTPUT_LEVEL_DBFS: -6;
    out property <float> MAX_OUTPUT_LEVEL_DBFS: 0;
    out property <int> MIN_COURSE_TUNE_SEMITONES: -12;
    out property <int> MAX_COURSE_TUNE_SEMITONES: 12;
    out property <float> SILENCE_LEVEL_DBFS: -70;
    out property <int> OSC_COURSE_TUNE_MINIMUM: -12;
    out property <int> OSC_COURSE_TUNE_MAXIMUM: 12;
    out property <int> OSC_FINE_TUNE_MINIMUM: -63;
    out property <int> OSC_FINE_TUNE_MAXIMUM: 63;
    out property <float> OSC_CLIPPER_BOOST_MINIMUM: 0;
    out property <float> OSC_CLIPPER_BOOST_MAXIMUM: 100;
    out property <float> OSC_PARAMETER1_MINIMUM: 0;
    out property <float> OSC_PARAMETER1_MAXIMUM: 100;
    out property <float> OSC_PARAMETER2_MINIMUM: 0;
    out property <float> OSC_PARAMETER2_MAXIMUM: 100;

    out property <[string]> OSC_WAVE_SHAPES: [
        "Sine",
        "Triangle",
        "Square",
        "Saw",
        "Pulse",
        "Ramp",
        "GigaSaw",
        "AM",
        "FM",
        "Noise"
    ];

    out property <[string]> LFO_WAVE_SHAPES: ["Sine", "Triangle", "Square", "Saw", "Ramp", "GigaSaw", "Noise"];

    out property <[string]> MIDI_CHANNELS: [
        "Omni",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16"
    ];
}
