import { Theme } from "theme.slint";
import {
    Panel,
    PanelLabel,
    EffectLabel,
    VerticalSpacer,
    ToggleSwitch,
    HorizontalSpacer,
} from "components.slint";
import { Switch } from "std-widgets.slint";
import {
    EffectBox,
    Wavefolder,
    Clipper,
    Gate,
    Rectifier,
    Bitshifter,
    Saturation,
    Compressor,
} from "effects.slint";

export component EffectsPanel inherits Panel {
    in property <string> title;

    callback effect_enabled(int, bool);
    callback effect_parameter_changed(int, int, float);

    VerticalLayout {
        padding: Theme.effects-panel-padding;
        spacing: Theme.effects-panel-spacing;
        alignment: start;

        VerticalLayout {
            row1 := HorizontalLayout {
                padding: Theme.effect-box-padding;
                spacing: Theme.effect-box-spacing;

                Wavefolder {
                    effect-index: 0;
                    is_enabled: false;
                    effect_enabled(effect-index, is_enabled) => {
                        effect_enabled(effect-index, is_enabled);
                    }
                    effect_parameter_changed(effect_index, parameter_index, value) => {
                        effect_parameter_changed(effect_index, parameter_index, value);
                    }
                }

                VerticalSpacer {
                    left-padding: 0px;
                    right-padding: 0px;
                }

                Clipper {
                    effect-index: 1;
                    is_enabled: false;
                    effect_enabled(effect-index, is_enabled) => {
                        effect_enabled(effect-index, is_enabled);
                    }
                    effect_parameter_changed(effect_index, parameter_index, value) => {
                        effect_parameter_changed(effect_index, parameter_index, value);
                    }
                }

                VerticalSpacer {
                    left-padding: 0px;
                    right-padding: 0px;
                }

                Gate {
                    effect-index: 2;
                    is_enabled: false;
                    effect_enabled(effect-index, is_enabled) => {
                        effect_enabled(effect-index, is_enabled);
                    }
                    effect_parameter_changed(effect_index, parameter_index, value) => {
                        effect_parameter_changed(effect_index, parameter_index, value);
                    }
                }

                VerticalSpacer {
                    left-padding: 0px;
                    right-padding: 0px;
                }

                Rectifier {
                    effect-index: 3;
                    is_enabled: false;
                    effect_enabled(effect-index, is_enabled) => {
                        effect_enabled(effect-index, is_enabled);
                    }
                    effect_parameter_changed(effect_index, parameter_index, value) => {
                        effect_parameter_changed(effect_index, parameter_index, value);
                    }
                }

                VerticalSpacer {
                    left-padding: 0px;
                    right-padding: 0px;
                }

                Bitshifter {
                    effect-index: 4;
                    is_enabled: false;
                    effect_enabled(effect-index, is_enabled) => {
                        effect_enabled(effect-index, is_enabled);
                    }
                    effect_parameter_changed(effect_index, parameter_index, value) => {
                        effect_parameter_changed(effect_index, parameter_index, value);
                    }
                }
            }

            row2 := HorizontalLayout {
                padding: Theme.effect-box-padding;
                spacing: Theme.effect-box-spacing;

                Saturation {
                    effect-index: 5;
                    is_enabled: false;
                    effect_enabled(effect-index, is_enabled) => {
                        effect_enabled(effect-index, is_enabled);
                    }
                    effect_parameter_changed(effect_index, parameter_index, value) => {
                        effect_parameter_changed(effect_index, parameter_index, value);
                    }
                }

                VerticalSpacer {
                    left-padding: 0px;
                    right-padding: 0px;
                }

                Compressor {
                    effect-index: 6;
                    is_enabled: false;
                    effect_enabled(effect-index, is_enabled) => {
                        effect_enabled(effect-index, is_enabled);
                    }
                    effect_parameter_changed(effect_index, parameter_index, value) => {
                        effect_parameter_changed(effect_index, parameter_index, value);
                    }
                }

                VerticalSpacer {
                    left-padding: 0px;
                    right-padding: 0px;
                }
            }
        }
    }
}
