import { Panel, PanelLabel, VerticalSpacer, HorizontalParameterSlider, VerticalIntSlider, FilterSlider, IntSpinBox, WaveShapeDropDown,
HorizontalSpacer } from "components.slint";
import { VerticalSlider, HorzontalSlider } from "custom-widgets.slint";
import { Theme } from "../ui/theme.slint";


export component FilterControlsPanel inherits Panel {
    in-out property <string> title;

    VerticalLayout {
        padding: Theme.osc-controls-panel-padding;
        spacing: Theme.osc-controls-panel-spacing;
        alignment: start;

        PanelLabel {
            label: title;
        }

        HorizontalLayout {
            alignment: start;

            cutoff := FilterSlider {
                label: "Cutoff";
                default-value: 100;
                width: 60px;
                slider-height: 220px;
            }

            resonance := FilterSlider {
                label: "Resonance";
                default-value: 0;
                slider-height: 220px;
            }
        }

        HorizontalSpacer { }
    }
}

export component OscControlsPanel inherits Panel {
    in-out property <string> title;

    VerticalLayout {
        padding: Theme.osc-controls-panel-padding;
        spacing: Theme.osc-controls-panel-spacing;
        alignment: start;

        PanelLabel {
            label: title;
        }

        wave-shape := WaveShapeDropDown {
            label: "Wave Shape";
            default-model: ["Sine", "Saw", "Square", "Triangle"];
            dropdown-width: 220px;
        }

        course-tune := IntSpinBox {
            label: "Course Tune";
            value-postfix: "semitones";
            step: 1;
            minimum: -12;
            maximum: 12;
            default-value: 0;
            spinbox-width: 220px;
        }

        fine-tune := HorizontalParameterSlider {
            label: "Fine Tune";
            value-postfix: "cents";
            minimum: -63;
            maximum: 63;
            default-value: 0;
            slider-width: 220px;
        }

        clip-boost := HorizontalParameterSlider {
            label: "Clipper Boost";
            value-postfix: "dbfs";
            minimum: 0;
            maximum: 30;
            default-value: 0;
            slider-width: 220px;
        }

        param1 := HorizontalParameterSlider {
            label: "Parameter 1";
            minimum: 0;
            maximum: 100;
            default-value: 0;
            slider-width: 220px;
        }

        param3 := HorizontalParameterSlider {
            label: "Parameter 2";
            minimum: 0;
            maximum: 100;
            default-value: 0;
            slider-width: 220px;
        }
    }
}

export component OscillatorsPanel inherits Panel {
    HorizontalLayout {
        padding: Theme.oscillator-panel-padding;
        spacing: Theme.oscillator-panel-spacing;

        osc1 := OscControlsPanel {
            title: Theme.osc-controls-panel-title-1;
            height: parent.height;
            width: parent.width / 5;
        }

        osc2 := OscControlsPanel {
            title: Theme.osc-controls-panel-title-2;
            height: parent.height;
            width: parent.width / 5;
        }

        osc3 := OscControlsPanel {
            title: Theme.osc-controls-panel-title-3;
            height: parent.height;
            width: parent.width / 5;
        }

        sub_osc := OscControlsPanel {
            title: Theme.osc-controls-panel-title-sub;
            height: parent.height;
            width: parent.width / 5;
        }

        filter := FilterControlsPanel {
            title: "Filter";
            width: parent.width / 5;
        }
    }
}
