import { Panel, PanelLabel, VerticalSpacer, HorizontalParameterSlider, CenteredParameterSlider, VerticalIntSlider, FilterSlider, IntSpinBox,
DropDownMenu, HorizontalSpacer, SectionLabel } from "components.slint";
import { VerticalSlider, HorzontalSlider, BalanceSlider } from "custom-widgets.slint";
import { Theme } from "theme.slint";
import { Constant } from "constants.slint";


export component OscControlsPanel inherits Panel {
    in-out property <string> title;

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            padding: Theme.osc-controls-panel-padding;
            spacing: Theme.osc-controls-panel-spacing;
            alignment: start;

            PanelLabel {
                label: title;
            }

            wave-shape := DropDownMenu {
                label: "Wave Shape";
                default-model: Constant.WAVE_SHAPES;
                dropdown-width: Theme.oscillator-panel-widget-width;
            }

            course-tune := IntSpinBox {
                label: "Course Tune";
                value-postfix: "semitones";
                step: 1;
                minimum: -12;
                maximum: 12;
                default-value: 0;
                spinbox-width: Theme.oscillator-panel-widget-width;
            }

            fine-tune := CenteredParameterSlider {
                label: "Fine Tune";
                value-postfix: "cents";
                minimum: -63;
                maximum: 63;
                slider-width: Theme.oscillator-panel-widget-width;
            }

            clip-boost := HorizontalParameterSlider {
                label: "Clipper Boost";
                value-postfix: "dbfs";
                minimum: 0;
                maximum: 30;
                default-value: 0;
                slider-width: Theme.oscillator-panel-widget-width;
            }

            param1 := HorizontalParameterSlider {
                minimum: 0;
                maximum: 100;
                default-value: 0;
                slider-width: Theme.oscillator-panel-widget-width;
            }

            param3 := HorizontalParameterSlider {
                minimum: 0;
                maximum: 100;
                default-value: 0;
                slider-width: Theme.oscillator-panel-widget-width;
            }
        }
    }
}

export component OscillatorsPanel inherits Panel {

    HorizontalLayout {
        padding: Theme.oscillator-panel-padding;
        spacing: Theme.oscillator-panel-spacing;

        osc1 := OscControlsPanel {
            title: Theme.osc-controls-panel-title-1;
            width: Theme.oscillator-panel-section-width;
        }

        osc2 := OscControlsPanel {
            title: Theme.osc-controls-panel-title-2;
            width: Theme.oscillator-panel-section-width;
        }

        osc3 := OscControlsPanel {
            title: Theme.osc-controls-panel-title-3;
            width: Theme.oscillator-panel-section-width;
        }

        sub_osc := OscControlsPanel {
            title: Theme.osc-controls-panel-title-sub;
            width: Theme.oscillator-panel-section-width;
        }
    }
}
