import { Theme } from "theme.slint";
import { Constant } from "constants.slint";
import {
    MomentaryButton,
    Panel,
    PanelLabel,
    ComponentLabel,
    DropDownMenu,
    HorizontalSpacer,
    VerticalControlLabel,
} from "components.slint";
import { Button, StandardButton } from "std-widgets.slint";

export struct AudioDevice {
    output-devices: [string],
    output-device-index: int,
    left-channels: [string],
    left-channel-index: int,
    right-channels: [string],
    right-channel-index: int,
    sample-rates: [string],
    sample-rate-index: int,
}

export struct MidiPort {
    input-ports: [string],
    input-port-index: int,
    channels: [string],
    channel-index: int,
}

export component AudioSettings inherits VerticalLayout {

    in property <AudioDevice> audio-device-values;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);

    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;

    device := DropDownMenu {
        label: "Output Device";
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.output-devices;
        value-index: audio-device-values.output-device-index;
        drop_down_changed(device) => {
            audio-output-device-changed(device);
        }
    }

    HorizontalLayout {
        padding: Theme.osc-controls-panel-padding;
        spacing: Theme.osc-controls-panel-spacing;

        left := DropDownMenu {
            label: "Left Channel";
            value-list: audio-device-values.left-channels;
            value-index: audio-device-values.left-channel-index;
            drop_down_changed(left) => {
                audio-output-left-channel-changed(left);
            }
        }

        right := DropDownMenu {
            label: "Right Channel";
            value-list: audio-device-values.right-channels;
            value-index: audio-device-values.right-channel-index;
            drop_down_changed(right) => {
                audio-output-left-channel-changed(right);
            }
        }
    }

    sample := DropDownMenu {
        label: "Sample Rate";
        enabled: false;
        dropdown-width: Theme.oscillator-panel-widget-width;
        value-list: audio-device-values.sample-rates;
        value-index: audio-device-values.sample-rate-index;
        drop_down_changed(rate) => {
            audio-sample-rate-changed(rate);
        }
    }
}

export component MidiSettings inherits VerticalLayout {
    in property <MidiPort> midi-port-values;

    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);

    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;

    port := DropDownMenu {
        label: "Input Port";
        value-list: midi-port-values.input-ports;
        value-index: midi-port-values.input-port-index;
        dropdown-width: Theme.oscillator-panel-widget-width;
        drop_down_changed(left) => {
            midi-input-port-changed(left);
        }
    }

    channel := DropDownMenu {
        label: "Channel";
        value-list: midi-port-values.channels;
        value-index: midi-port-values.channel-index;
        dropdown-width: Theme.oscillator-panel-widget-width;
        drop_down_changed(left) => {
            midi-input-channel-changed(left);
        }
    }
}

export component SettingsIcon inherits Image {
    source: Theme.settings-image;
    height: Theme.header-logo-height;
    width: Theme.header-logo-height;
    colorize: touch.pressed ? black : transparent;
    callback open-settings();

    touch := TouchArea {
        changed pressed => {
            if (self.pressed) {
                open-settings();
            }
        }
    }
}

export component SettingsWindow inherits PopupWindow {
    in property <AudioDevice> audio-device-values;
    in property <MidiPort> midi-port-values;

    callback audio-output-device-changed(string);
    callback audio-output-left-channel-changed(string);
    callback audio-output-right-channel-changed(string);
    callback audio-sample-rate-changed(string);
    callback midi-input-port-changed(string);
    callback midi-input-channel-changed(string);

    width: Theme.settings-panel-width;
    height: Theme.settings-panel-height;
    x: Theme.window-width / 2 - Theme.settings-panel-width / 2;
    y: Theme.window-height / 2 - Theme.settings-panel-height / 2;
    close-policy: no-auto-close;

    Rectangle {
        background: Theme.settings-window-background;
        border-width: Theme.settings-window-border-width;
        border-color: Theme.settings-window-border-colour;
        border-bottom-left-radius: Theme.settings-window-border-radius;
        border-bottom-right-radius: Theme.settings-window-border-radius;
        border-top-left-radius: Theme.settings-window-border-radius;
        border-top-right-radius: Theme.settings-window-border-radius;

        VerticalLayout {
            padding: Theme.osc-controls-panel-padding;
            spacing: Theme.osc-controls-panel-spacing;
            alignment: start;

            HorizontalLayout {
                padding: Theme.osc-controls-panel-padding;
                spacing: Theme.osc-controls-panel-spacing;
                alignment: start;

                VerticalLayout {
                    padding: Theme.osc-controls-panel-padding;
                    spacing: Theme.osc-controls-panel-spacing;
                    alignment: start;

                    PanelLabel {
                        label: "Audio Settings";
                    }

                    AudioSettings {
                        audio-device-values: audio-device-values;

                        audio-output-device-changed(device) => {
                            audio-output-device-changed(device);
                        }
                        audio-output-left-channel-changed(left) => {
                            audio-output-left-channel-changed(left);
                        }
                        audio-output-right-channel-changed(right) => {
                            audio-output-right-channel-changed(right);
                        }
                        audio-sample-rate-changed(rate) => {
                            audio-sample-rate-changed(rate);
                        }
                    }
                }

                VerticalLayout {
                    padding: Theme.osc-controls-panel-padding;
                    spacing: Theme.osc-controls-panel-spacing;
                    alignment: start;

                    PanelLabel {
                        label: "Midi Settings";
                    }

                    MidiSettings {
                        midi-port-values: midi-port-values;
                        midi-input-port-changed(port) => {
                            midi-input-port-changed(port);
                        }
                        midi-input-channel-changed(channel) => {
                            midi-input-channel-changed(channel);
                        }
                    }
                }
            }

            HorizontalSpacer { }

            StandardButton {
                kind: close;
                clicked => {
                    root.close();
                }
            }
        }
    }
}
