import { Theme } from "theme.slint";
import { Constant } from "constants.slint";
import { MomentaryButton, Panel, PanelLabel, ComponentLabel, DropDownMenu, HorizontalSpacer, VerticalControlLabel } from "components.slint";
import { Button, StandardButton } from "std-widgets.slint";


export component AudioSettings inherits VerticalLayout {
    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;

    device := DropDownMenu {
        label: "Output Device";
        default-model: ["Focusrite Scarlett", "Builtin Speakers", "External Headphones"];
        dropdown-width: Theme.oscillator-panel-widget-width;
    }

    HorizontalLayout {
        padding: Theme.osc-controls-panel-padding;
        spacing: Theme.osc-controls-panel-spacing;

        left := DropDownMenu {
            label: "Left Channel";
            default-model: ["1", "2", "3", "4"];
        }

        right := DropDownMenu {
            label: "Right Channel";
            default-model: ["1", "2", "3", "4"];
        }
    }

    sample := DropDownMenu {
        label: "Sample Rate";
        default-model: ["44,100", "48,000", "96,000"];
        dropdown-width: Theme.oscillator-panel-widget-width;
    }
}

export component MidiSettings inherits VerticalLayout {
    padding: Theme.osc-controls-panel-padding;
    spacing: Theme.osc-controls-panel-spacing;

    port := DropDownMenu {
        label: "Input Port";
        default-model: ["MidiHub", "Focusrite Scarlett"];
        dropdown-width: Theme.oscillator-panel-widget-width;
    }

    channel := DropDownMenu {
        label: "Channel";
        default-model: Constant.MIDI_CHANNELS;
        dropdown-width: Theme.oscillator-panel-widget-width;
    }
}

export component SettingsIcon inherits Image {
    source: Theme.settings-image;
    height: Theme.header-logo-height;
    width: Theme.header-logo-height;
    colorize: touch.pressed ? black : transparent;
    callback open-settings();

    touch := TouchArea {
        changed pressed => {
            if (self.pressed) {
                open-settings();
            }
        }
    }
}

export component SettingsWindow inherits PopupWindow {
    width: Theme.settings-panel-width;
    height: Theme.settings-panel-height;
    x: Theme.window-width / 2 - Theme.settings-panel-width / 2;
    y: Theme.window-height / 2 - Theme.settings-panel-height / 2;
    close-policy: no-auto-close;

    Rectangle {
        background: Theme.settings-window-background;
        border-width: Theme.settings-window-border-width;
        border-color: Theme.settings-window-border-colour;
        border-bottom-left-radius: Theme.settings-window-border-radius;
        border-bottom-right-radius: Theme.settings-window-border-radius;
        border-top-left-radius: Theme.settings-window-border-radius;
        border-top-right-radius: Theme.settings-window-border-radius;

        VerticalLayout {
            padding: Theme.osc-controls-panel-padding;
            spacing: Theme.osc-controls-panel-spacing;
            alignment: start;

            HorizontalLayout {
                padding: Theme.osc-controls-panel-padding;
                spacing: Theme.osc-controls-panel-spacing;
                alignment: start;

                VerticalLayout {
                    padding: Theme.osc-controls-panel-padding;
                    spacing: Theme.osc-controls-panel-spacing;
                    alignment: start;

                    PanelLabel {
                        label: "Audio Settings";
                    }

                    AudioSettings { }
                }

                VerticalLayout {
                    padding: Theme.osc-controls-panel-padding;
                    spacing: Theme.osc-controls-panel-spacing;
                    alignment: start;

                    PanelLabel {
                        label: "Midi Settings";
                    }

                    MidiSettings { }
                }
            }

            HorizontalSpacer { }

            StandardButton {
                kind: close;
                clicked => {
                    root.close();
                }
            }
        }
    }
}
