import { Palette } from "std-widgets.slint";

/*  Palette - Fluent Dark
    foreground - white
    background - dark gray
    alternate f - white
    alternate b - lighter dark grey than  background background
    control f - white
    control b - Transparent
    accent f - black
    accent b - Control tracks in the theme
    selection f - black
    selection b - other blue
*/

export global Theme {

    // Main Window
    out property <string> window-title: "Accidental Synthesizer";
    in-out property <image> icon: @image-url("../../images/icon.png");
    out property <length> window-width: 1300px;
    out property <length> window-height: 800px;
    out property <length> window-border-width: 2px;
    out property <color> window-background: Palette.background;
    out property <color> window-border-colour: Palette.border;
    out property <length> window-border-radius: 15px;

    // Text Defaults
    out property <length> default-text-size: 14px;
    out property <string> default-font-family: "HackNerdFontMono";
    out property <int> default-font-weight: 400;
    out property <color> default-font-color: Palette.foreground;

    // Panel Defaults
    out property <length> panel-border-width: 2px;
    out property <color> panel-background: Palette.background;
    out property <color> panel-border-colour: Palette.border;
    out property <length> panel-border-radius: 0px;
    out property <length> panel-label-font-size: 16px;
    out property <int> panel-label-font-weight: 600;
    out property <color> spacer-color: Palette.border;
    out property <length> section-label-font-size: 12px;
    out property <int> section-label-font-weight: 400;
    out property <length> component-label-font-size: 12px;
    out property <int> component-label-font-weight: 400;

    // Header Panel
    in-out property <image> header-logo: @image-url("../../images/transparent.png");
    out property <length> header-logo-height: 20px;
    out property <ImageHorizontalAlignment> header-logo-alignment: left;
    out property <length> header-panel-padding: 10px;
    out property <length> header-panel-spacing: 0px;
    out property <length> header-panel-height: 40px;
    out property <length> header-version-font-size: 10px;
    out property <string> header-version-prefix: "v";
    out property <brush> header-panel-background: @radial-gradient(circle, #101010 0%, #101035 100%);

    // Custom Widgets
    out property <color> handle-border-colour: Palette.background;
    out property <color> slider-indicator-colour: #0066CC;
    out property <color> handle-background-colour: #0066CC;
    out property <color> slider-track-colour: Palette.border;
    out property <length> slider-track-width: 6px;
    out property <length> slider-track-height: 100px;

    // Main Tabs
    out property <string> tab-title-oscillators: "Oscillators";
    out property <string> tab-title-modulation: "Modulation";
    out property <string> tab-title-effects: "Effects";
    out property <string> tab-title-settings: "Settings";

    // Oscillators Panel
    out property <length> oscillator-panel-height: 530px;
    out property <length> oscillator-panel-padding: 0px;
    out property <length> oscillator-panel-spacing: 0px;

    // Osciallator Controls Panel
    out property <length> osc-controls-panel-padding: 8px;
    out property <length> osc-controls-panel-spacing: 20px;
    out property <string> osc-controls-panel-title-1: "Oscillator 1";
    out property <string> osc-controls-panel-title-2: "Oscillator 2";
    out property <string> osc-controls-panel-title-3: "Oscillator 3";
    out property <string> osc-controls-panel-title-sub: "Sub Oscillator";

    // Global Panel
    out property <length> global-panel-height: 220px;
    out property <length> global-panel-padding: 10px;
    out property <length> global-panel-spacing: 0px;
    out property <string> output-mixer-label: "Output";
    out property <string> osc-mixer-label: "Oscillator Mixer";
    out property <string> osc-mixer-title-1: "Osc 1";
    out property <string> osc-mixer-title-2: "Osc 2";
    out property <string> osc-mixer-title-3: "Osc 3";
    out property <string> osc-mixer-title-sub: "Sub";
    out property <string> mixer-level-label: "Level";
    out property <string> mixer-balance-label: "Balance";
    out property <string> mixer-mute-label: "Mute";
}
