import { Palette } from "std-widgets.slint";

/*  Palette - Fluent Dark
    foreground - white
    background - dark gray
    alternate f - white
    alternate b - lighter dark grey than  background background
    control f - white
    control b - Transparent
    accent f - black
    accent b - Control tracks in the theme
    selection f - black
    selection b - other blue
*/

export global Theme {

    // Main Window
    out property <string> window-title: "Accidental Synthesizer";
    in-out property <image> icon: @image-url("images/icon.png");
    in-out property <image> settings-image: @image-url("images/gear.png");
    out property <length> window-width: 1300px;
    out property <length> window-height: 800px;
    out property <length> window-border-width: 2px;
    out property <color> window-background: Palette.background;
    out property <color> window-border-colour: Palette.border;
    out property <length> window-border-radius: 15px;

    // Text Defaults
    out property <length> default-text-size: 14px;
    out property <string> default-font-family: "HackNerdFontMono";
    out property <int> default-font-weight: 400;
    out property <color> default-font-color: Palette.foreground;
    out property <color> default-font-disabled-color: Palette.control-background;

    // Panel Defaults
    out property <length> panel-border-width: 2px;
    out property <color> panel-background: Palette.background;
    out property <color> panel-border-colour: Palette.border;
    out property <length> panel-border-radius: 0px;
    out property <length> panel-label-font-size: 14px;
    out property <int> panel-label-font-weight: 600;
    out property <color> spacer-color: Palette.border;
    out property <length> section-label-font-size: 13px;
    out property <int> section-label-font-weight: 500;
    out property <length> component-label-font-size: 13px;
    out property <int> component-label-font-weight: 400;

    // Header Panel
    in-out property <image> header-logo: @image-url("images/header.png");
    out property <length> header-logo-height: 20px;
    out property <ImageHorizontalAlignment> header-logo-alignment: left;
    out property <length> header-panel-padding: 10px;
    out property <length> header-panel-spacing: 0px;
    out property <length> header-panel-height: 40px;
    out property <length> header-version-font-size: 10px;
    out property <string> header-version-prefix: "v";
    out property <brush> header-panel-background: @radial-gradient(circle, #000000 0%, #101035 100%);

    // Custom Widgets
    out property <color> handle-border-colour: Palette.background;
    out property <color> slider-indicator-colour: #0066CC;
    out property <color> handle-background-colour: slider-indicator-colour;
    out property <color> slider-track-colour: Palette.border;
    out property <length> slider-track-width: 6px;
    out property <length> slider-track-height: 100px;
    out property <string> control-label-default-string: "---";

    // Main Tabs
    out property <string> tab-title-oscillators: "Oscillators";
    out property <string> tab-title-effects: "Effects";

    // Oscillators Panel
    out property <length> oscillator-panel-height: 425px;
    out property <length> oscillator-panel-width: 600px;
    out property <length> oscillator-panel-padding: 0px;
    out property <length> oscillator-panel-spacing: 0px;
    out property <length> oscillator-panel-section-width: 250px;
    out property <length> oscillator-panel-widget-width: 200px;

    // Filter Panel
    out property <length> filter-panel-widget-width: 120px;
    out property <length> filter-panel-width: 300px;
    out property <string> filter-panel-label: "Filter";
    out property <string> filter-label-cutoff: "Cutoff";
    out property <string> filter-label-resonance: "Reso";
    out property <string> filter-label-poles: "Poles";
    out property <string> filter-label-key-tracking: "Key Tracking";
    out property <string> filter-label-envelope-amount: "EG Amount";
    out property <string> filter-label-lfo-amount: "LFO Amount";
    out property <string> filter-section-label-envelope: "Filter Envelope";
    out property <string> filter-label-envelope-attack: "Attack";
    out property <string> filter-label-envelope-decay: "Decay";
    out property <string> filter-label-envelope-sustain: "Sustain";
    out property <string> filter-label-envelope-release: "Release";
    out property <string> filter-label-envelope-inverted: "Inverted";
    out property <string> filter-section-label-lfo: "Filter LFO";
    out property <string> filter-label-lfo-frequency: "Frequency";
    out property <string> filter-label-lfo-wave-shape: "Wave Shape";
    out property <string> filter-label-lfo-phase: "Phase";
    out property <string> filter-label-lfo-reset: "Reset";

    // Global Panel
    out property <length> global-panel-height: 330px;
    out property <length> global-panel-width: 500px;
    out property <length> global-panel-padding: 5px;
    out property <length> global-panel-spacing: 10px;
    out property <string> output-mixer-label: "Output";
    out property <string> osc-mixer-label: "Mixer";
    out property <string> osc-mixer-title-1: "Osc 1";
    out property <string> osc-mixer-title-2: "Osc 2";
    out property <string> osc-mixer-title-3: "Osc 3";
    out property <string> osc-mixer-title-sub: "Sub";
    out property <string> mixer-level-label: "Level";
    out property <string> mixer-balance-label: "Balance";
    out property <string> mixer-mute-label: "Mute";
    out property <string> osc-options-section-label: "Oscillator Options";
    out property <string> osc-options-portamento-label: "Portamento";
    out property <string> osc-options-portamento-time-label: "Time";
    out property <string> osc-options-portamento-time-postfix: "ms";
    out property <string> osc-options-pitch-bend-range: "Pitch Bend Range";
    out property <string> osc-options-velocity-curve: "Velocity Curve";
    out property <string> osc-options-hard-sync: "Hard Sync";
    out property <string> osc-options-key-sync: "Key Sync";
    out property <string> amp-envelope-section-label: "Amp Envelope";
    out property <string> mod-wheel-section-label: "Mod Wheel";

    // Osciallator Controls Panel
    out property <length> osc-controls-panel-padding: 8px;
    out property <length> osc-controls-panel-spacing: 15px;
    out property <string> osc-controls-panel-title-1: "Oscillator 1";
    out property <string> osc-controls-panel-title-2: "Oscillator 2";
    out property <string> osc-controls-panel-title-3: "Oscillator 3";
    out property <string> osc-controls-panel-title-sub: "Sub Oscillator";
    out property <string> osc-controls-wave-shape: "Wave Shape";
    out property <string> osc-controls-fine-tune: "Fine Tune";
    out property <string> osc-controls-course-tune: "Course Tune";
    out property <string> osc-controls-clipper-boost: "Clipper Boost";
    out property <string> osc-controls-semitones: "semitones";
    out property <string> osc-controls-cents: "cents";
    out property <string> osc-controls-dbfs: "dbfs";

    // Settings Window
    out property <length> settings-panel-width: 600px;
    out property <length> settings-panel-height: 300px;
    out property <length> settings-window-border-width: 2px;
    out property <color> settings-window-background: Palette.background;
    out property <color> settings-window-border-colour: Palette.background.brighter(3);
    out property <length> settings-window-border-radius: 10px;
}
